### ISSUE TITLE
Every Comment in config.yml and lang.yml is duplicated

### ISSUE THREAD

**Issue by Chris6ix** [Realizedd/Duels#62]
Hey,
While re-configuring your Duels Plugin (I removed it for 1.17.1 and re-added it for 1.18.1 as it's now supported again) I saw that every comment inside both config.yml and lang.yml are duplicated...which looks very weird...

Here are examples of what I mean:
![image](https://user-images.githubusercontent.com/65610536/148685634-0ec337ab-a0f3-42c9-a8bd-0dd9f9b54fb9.png)

![image](https://user-images.githubusercontent.com/65610536/148685550-dff39b5b-b692-408a-b791-68ee11d895c1.png)

![image](https://user-images.githubusercontent.com/65610536/148685595-f9d175fc-86a8-46ba-9e55-52732c95fdfb.png)

I'm using Duels 3.5.1 on Paper 1.18.1 #141

**Comment by Realizedd** [comment]
Fixed in 4c7f841. I've pushed a silent update to the SpigotMC page, so you can just redownload to get a jar containing the fix. Afterward, stop the server, delete the current config.yml, and rename the previous config stored as config-<number>.yml back to config.yml to properly upgrade the configuration without duplicates this time.

**Comment by Chris6ix** [comment]
Okay thank you very much :)
